### ISSUE TITLE
Add a correct ML model to your story...

### ISSUE THREAD

**Issue by kaiwaehner** [fbascheper/kafka-tf-burglar-alerts-demo#1]
Hi Erik-Berndt,

just watched the recording of your talk. 
I really like the whole story and your architecture (including nice custom connectors and converters). 

I highly recommend to add (i.e. train) an analytic model which really does what you explain in your use cases - as your demo is not related to the story at all. If you just demo the "tensorflow hello world" instead and integrate this into your Kafka Streams application, many people are confused (as you see in the Q&A of your talk).

You spent a lot of time into connectors, the whole setup, etc. Therefore, it would be great to complete the story. Transfer learning is not that hard and many examples are available for images. Just pick a tutorial and replace something like "fruits" with the pictures from your camera. 
(though, it is still not done in an hour, and I get the point if you say you are interested and experienced in the development parts, not in the ML parts)

Just my two cents. Besides this "issue" a great talk! Thanks.

Kai

**Comment by fbascheper** [comment]
Hi Kai,

Thanks for the feedback! I am continuously thinking about this 'issue', and not only because I'd really like to repeat this talk at other conferences. So any suggestions how to realise this are more than welcome. The thing is, I really fear the privacy laws here in Europe (think GDPR).  

My current idea is to start with 'empty' images from my camera and add 'random' people from the internet. Then again qualifying random people in a talk as 'burglar' does not seem very appropriate either. WDYT?

**Comment by kaiwaehner** [comment]
I am not sure about this privacy issue. If you just make pictures of your home and only your family or friends (who agree on this), it should not be a problem at all. Or you use pictures / faces from some public available data sets (I am sure there is something).

I was especially surprised that you said this in the talk and afterwards you made a picture of the audience in the room and tried to upload it :-)

By the way: We also do Kafka Meetups in all big cities in Europe. We could also organize to add your talk where you want :-) Just drop me an email if you are interested.

**Comment by fbascheper** [comment]
Maybe you are right, people in public datasets should be all right. I'll have a look around and see what I can find. I'll update my findings in this thread. 

The picture of the audience was more of a spontaneous idea. Maybe that was inappropriate, indeed. Then again, AFAIK everyone at the conference had already agreed to be photographed and or filmed.

**Comment by fbascheper** [comment]
I've created a [separate project](https://github.com/fbascheper/kafka-tf-burglar-alerts-demo-model) to address this issue. It's written in Python and uses `transfer learning` to create a model which I have copied back into [this project](https://github.com/fbascheper/kafka-tf-burglar-alerts-demo/tree/develop/src/main/resources/tensorflow/model).

The training and validation datatset is constituted using the [INRIA Person Dataset](http://pascal.inrialpes.fr/data/human/). And I've removed backgrounds from these images using the [Remove Image Background](https://www.remove.bg/) website.

**Comment by fbascheper** [comment]
@kaiwaehner Thanks again for your comment. I'm closing this issue as resolved (see above).
Any other suggestions and / or improvements, either regarding this application or the way I built the TensorFlow model, are very welcome of course.
